package com.meitu.greendaodemo.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.meitu.greendaodemo.bean.Computer;
import com.meitu.greendaodemo.bean.Student;

import com.meitu.greendaodemo.greendao.dao.ComputerDao;
import com.meitu.greendaodemo.greendao.dao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig computerDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final ComputerDao computerDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        computerDaoConfig = daoConfigMap.get(ComputerDao.class).clone();
        computerDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        computerDao = new ComputerDao(computerDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(Computer.class, computerDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        computerDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public ComputerDao getComputerDao() {
        return computerDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
